name: PR Title Check

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR title contains WIP
        run: |
          echo "🔍 Checking PR title..."
          if echo "${{ github.event.pull_request.title }}" | grep -iq 'WIP'; then
            echo "❌ PR title contains 'WIP'. Failing check."
            exit 1
          fi
          echo "✅ Title looks good."
